# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-27 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_bank_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='品牌')),
                ('sex', models.IntegerField(verbose_name='性别')),
                ('pic', models.ImageField(upload_to='img/pic', verbose_name='图片')),
            ],
        ),
    ]
